### ISSUE TITLE
Unable to call score function, error: "setting an array element with a sequence"

### ISSUE THREAD

**Issue by vickeywangvw** [zillow/luminaire#89]
We met the problem when we tried to call the score function in WindowDensity API (Luminaire Libary). The error message was "setting an array element with a sequence". We searched online and asked for other professionals' experience but still failed to solve it. Can anybody help us with it? Thanks in advance~~

Luminaire Reference: https://zillow.github.io/luminaire/_modules/luminaire/model/window_density.html#WindowDensityHyperParams

![1](https://user-images.githubusercontent.com/71788582/113187258-a2a3fa00-9226-11eb-90d4-9fdd8edaa240.PNG)
![2](https://user-images.githubusercontent.com/71788582/113187259-a33c9080-9226-11eb-9a9e-2015cb08cf3a.PNG)
![3](https://user-images.githubusercontent.com/71788582/113187261-a33c9080-9226-11eb-9980-b7721068fca4.PNG)
![5](https://user-images.githubusercontent.com/71788582/113187531-f7477500-9226-11eb-9845-a33501b50c36.png)
![6](https://user-images.githubusercontent.com/71788582/113187549-fc0c2900-9226-11eb-8637-dc552e72f97c.png)
![7](https://user-images.githubusercontent.com/71788582/113187561-fe6e8300-9226-11eb-902f-8b5627207399.png)

**Comment by sayanchk** [comment]
@vickeywangvw As suggested in the documentation, Luminaire automatically detects the suitable window size for the given data. This window size means the suitable size of the data that can be used for scoring to get most reliable scoring information. 

I can see the `pre_prc` has produced a suggested window size of 24 which is a day. That means you should be passing data of length 24 in order to score. That means you can pass data from `2021-03-17 22:00:00` to `2021-03-18 21:00:00` to score.

Another important note is you should be training using the time series data before `2021-03-17 22:00:00` in order to score the above window. The whole idea of the WindowDensity API is to check for anomalies for any _incoming_ data based on the previous information.

**Comment by dhruv7goyal** [comment]
Hi @sayanchk Is it also possible to detect anomalies on the trained dataset if we give the expected window size?

**Comment by sayanchk** [comment]
You can still do that if you specify the right window size. Although, this will not be a good idea since some information in the model will be generated based on the data since the model has already seen it (something like a data leak issue).

**Comment by dhruv7goyal** [comment]
Thanks for the prompt response, Understood. I wanted to check if there is a function to get the scores for a batch of windows. Lets say I have a batch of 5 windows and each window has a size of 10, hence I have 5*10 records in my input data frame to the scoring function and the output is 5 records with scores for each window.

**Comment by vickeywangvw** [comment]
> 2021-03-17 22:00:00

Thanks for your response. It successsfully solved our issue!

**Comment by dhruv7goyal** [comment]
Thats helpful thanks.
