### ISSUE TITLE
Unable to use data exploration "The training data observed continuous missing data near the end. Require more stable data to train"

### ISSUE THREAD

**Issue by eaglewarrior** [zillow/luminaire#91]
I have tried to use simple data and its giving these issues 

Here is the notebook
https://colab.research.google.com/drive/19muQTHoWxdh5fC1DQE2FpYu763fn-0zC?usp=sharing

**Comment by sayanchk** [comment]
@eaglewarrior The data you provided is monthly data but you are specifying `freq='D'` while initiating the DataExploration class object. That means it is expecting data to be daily and that's why it is complaining for missing data.

At this moment, Luminaire doesn't support monthly pandas offset. Kindly see the Luminaire documentation for currently supported offsets: https://zillow.github.io/luminaire/api_reference/exploration.html

**Comment by eaglewarrior** [comment]
![image](https://user-images.githubusercontent.com/18038147/126426957-99ed933b-3220-477a-a736-81b86df4db58.png)
Is this what is not a monthly data its daily

**Comment by sayanchk** [comment]
@eaglewarrior yes this is the Airline passengers data which is observed first day of the month at a monthly cadence.

**Comment by eaglewarrior** [comment]
Yes i tried some other dataset its working
